[package]
name = "USDB_mint"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.13.2"
ic-cdk-macros = "0.8.3"
candid = "0.10.4"
serde = { version = "1.0", features = ["derive"] }
