[package]
name = "notify_btc_recieved"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.13.6"
ic-cdk-macros = "0.6.10"
candid = "0.10.6"
serde = { version = "1.0", features = ["derive"] }
