[package]
name = "notify_btc_recieved"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.13.6"
ic-cdk-macros = "0.13.2"
candid = "0.10"
serde = { version = "1.0", features = ["derive"] }


[lib]
crate-type = ["cdylib"]